server:
  port: 9000

spring:
  datasource:
    url : jdbc:mysql://34.64.253.121:3306/FITSKIN?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: fitskin_user
    password: changeme
    driver-class-name: com.mysql.cj.jdbc.Driver

  # mysql 사용
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
        show_sql: true
        # SQL문을 가독성 있게 표현
        format_sql: true
        # 디버깅 정보 출력
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

  # logging
  logging:
    level:
      org:
        hibernate: info
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
